### ISSUE TITLE
URBAN-SED 

### ISSUE THREAD

**Issue by yangdongchao** [satvik-venkatesh/you-only-hear-once#1]
It is a great job!
But it seems that your model cannot get SOTA performance on Urban-sed dataset. In paper, “Sound event envelope estimation in polyphonicmixtures,”   in ICASSP 2019-2019 IEEE International Conference on Acoustics, Speech and Signal Processing(ICASSP). 
The segment-F score is 64% .

**Comment by satvik-venkatesh** [comment]
Thank you for mentioning this!
Agreed. The purpose of this paper is to propose a novel architecture and compare it with CRNN. The paper that you cited uses envelope estimation to improve model's performance. Perhaps, our model could be improved by incorporating envelope estimation. I will include a discussion about this in the next revision of the paper.

**Comment by yangdongchao** [comment]
> Thank you for mentioning this!
> Agreed. The purpose of this paper is to propose a novel architecture and compare it with CRNN. The paper that you cited uses envelope estimation to improve model's performance. Perhaps, our model could be improved by incorporating envelope estimation. I will include a discussion about this in the next revision of the paper.

Thanks for your reply. 
Another paper you should pay attention " Towards duration robust weakly supervised sound event detection". In this paper, author use CRNN framework with weakly label also get 64% F score on Urban-sed dataset, and the model is very lite.
Thanks for your code again. Your methods is very valuable for this SED fields.

**Comment by satvik-venkatesh** [comment]
Thank you :) Will do.
