### ISSUE TITLE
Our ideas are so close

### ISSUE THREAD

**Issue by xk-wang** [satvik-venkatesh/you-only-hear-once#4]
just like my paper and my code https://github.com/xk-wang/MusicYOLO. I started this research from June to July last year.

**Comment by satvik-venkatesh** [comment]
Hey thanks for sharing this. Could you please share a preprint? I am unable to view a PDF of the ICASSP paper.

**Comment by xk-wang** [comment]
> Hey thanks for sharing this. Could you please share a preprint? I am unable to view a PDF of the ICASSP paper.

Sorry, I don't have an arxiv account. You will be able to see it on IEEE Xplore after the ICASSP conference in May this year. If you need, you can leave an email adress and I'll send you the paper.

**Comment by satvik-venkatesh** [comment]
Sure, my email address is satvikvenkatesh@gmail.com. I look forward to reading it!
